service: <%= name %>

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 1024 # optional, in MB, default is 1024
  timeout: 6 # optional, in seconds, default is 6

  stage: ${env:SLS_AWS_STAGE}
  region: ${env:SLS_AWS_REGION}

  environment:
      PLACE: "holder"

  <% if (ddbTableName) { %>
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:UpdateItem
      Resource:
        Fn::GetAtt: [ <%= ddbTableName %>, Arn ]
  <% } %>

package:
  individually: true
  exclude:
    - ".*/**"

functions:
  <%= name %>:
    handler: build/index.handler
    environment:
    <% if (ddbTableName) { %>
      <%= ddbTableName %>:
        Ref: <%= ddbTableName %>
    <% } %>
    package:
      include:
        - build/**

    events:
      - http:
          path: <%= name %>
          method: get

<% if (ddbTableName) { %>
resources:
  Resources:
    <%= ddbTableName %>:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: <%= ddbTableName %>
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_IMAGE

<% } %>

custom:
  webpack:
    webpackConfig: '../../webpack.config.js'
